# + -------------------------------------------------------------------------------- + #
# | MESSAGE, ERRORMESSAGE SETTINGS ( 메시지 설정 )
# | 유저에게 출력되지 않을 메세지는 해당 라인을 지우시거나
# | 해당 라인의 제일 앞에 '#' 을 붙여 주석으로 처리하시면 됩니다.
# + -------------------------------------------------------------------------------- + #
messages:
  # (메시지 앞에 붙는) 접두사
  prefix: ' &f귀환&b토큰 | &r'

  # 귀환토큰을 설정하였을 때 출력되는 메시지
  setReverieToken: '&f손에 든 아이템을 귀환토큰으로 설정하였습니다.'

  # 귀환토큰을 사용하게 되었을 때 출력되는 메시지
  useReverieToken: '&f귀환토큰을 사용해 귀환을 하였습니다.'

  # 콘피그를 리로드 하였을 때 출력되는 메시지
  reloadComplete: '&a콘피그를 리로드하였습니다.'

errorMessages:
  # 권한이 없을 때 출력되는 메시지
  notAnOperator: '&c해당 명령어를 실행할 권한이 없습니다.'

  # 콘솔에서 사용이 불가능한 명령어를 사용하려고 하였을 때 출력되는 메시지
  noConsoleCommand: '&c콘솔에서는 사용이 불가능한 명령어입니다.'

  # 잘못된 명령어를 사용하였을 때 출력되는 메시지
  wrongCommand: '&c잘못된 명령어입니다. (다시 시도해주세요)'

  # 손에 아이템을 들지않고 귀환토큰을 설정하려고 했을 때 출력되는 메시지
  noItemInHand: '&c손에 아이템을 들어주세요.'

  # 저장된 위치 문자열에서 오류가 발생할 때 출력되는 메시지
  invalidLocationString: '&c저장된 위치 문자열이 유효하지 않습니다.'

  # 저장된 위치의 문자열 형식이 올바르지 않을 때 출력되는 메시지
  incorrectLocationFormat: '&c저장된 위치 문자열 형식이 올바르지 않습니다.'