name: ST-ReverieToken
main: net.starly.reverietoken.ReverieToken
author: Starly Team
website: http://starly.kr/

description: ReverieToken Plugin.

softdepend:
  - ST-Core

version: 1.0.1
api-version: 1.13

permissions:
  starly.reverietoken.set:
    description: 귀환토큰을 설정합니다.
  starly.reverietoken.reload:
    description: 구성파일을 다시 불러옵니다.
  starly.reverietoken.*:
    description: ST-ReverieToken 명령어에 대한 모든 권한
    children:
      - starly.reverietoken.set
      - starly.reverietoken.reload

commands:
  귀환토큰: